### ISSUE TITLE
Shift in conv2_8bit and conv_4bit

### ISSUE THREAD

**Issue by jypark1257** [alexmr09/Mixed-precision-Neural-Networks-on-RISC-V-Cores#5]
I understand how the conv2_2bits works, 

but for conv2_4bits and conv_8bits,  can you explain why there is "<<1" and "<<2" repectively in the function declaration?

Thank you

**Comment by alexmr09** [comment]
Hello,

The purpose of these shifts in the function declaration is to align the dimensions of the generated weight matrices after applying the Mixed Precision Quantization scheme for compression.

**Comment by jypark1257** [comment]
thank you
