### ISSUE TITLE
Packing weight & activation issue

### ISSUE THREAD

**Issue by pdh930105** [alexmr09/Mixed-precision-Neural-Networks-on-RISC-V-Cores#6]
Hello, I have a question.

Through ```combined_values```, I confirmed that the input is packed in the **in_channel direction**, and the weight is packed in the **out_channel direction**.

Based on this result, assuming an 8-bit weight and 8-bit input calculation, I observed that activations are packed into 4 elements along the in_channel direction (32-bit), while weights are packed into 4 elements along the out_channel direction (32-bit) within one ```nm_8bit```.

In your paper, it seems that weights are represented as ```PackW = (w11, w22, w33, w44)``` and activations as ```PackA = (a1, a2, a3, a4)```, allowing computations like ```(w11 * a1, w22 * a2, w33 * a3, w44 * a4)``` to proceed correctly. However, in the actual code, weights are packed as ```PackW = (w11, w21, w31, w41)``` instead, which seems to make the computations difficult to execute properly.

Thank you

**Comment by alexmr09** [comment]
Hello,

Thank you for your observation! You're absolutely correct—the way the weights and inputs are packed in our implementation differs from the representation in the paper. In the paper, the packing method was simplified for illustrative purposes to demonstrate how we compress the weight and input variables into a 32-bit number.

In the current implementation, the packing approach is designed to maximize input reuse across multiple calculations. Here’s an example to clarify:

    1st MAC instruction:
        PackW = (w11, w21, w31, w41)
        PackA = (a1, a2, a3, a4)
        → Computations for 1st Accumulator

    2nd MAC instruction:
        PackW = (w12, w22, w32, w42)
        PackA = (a1, a2, a3, a4)
        → Computations for 2nd Accumulator

    3rd MAC instruction:
        PackW = (w13, w23, w33, w43)
        PackA = (a1, a2, a3, a4)
        → Computations for 3rd Accumulator

    4th MAC instruction:
        PackW = (w14, w24, w34, w44)
        PackA = (a1, a2, a3, a4)
        → Computations for 4th Accumulator

I hope this clarifies the reasoning behind the packing strategy. Please let me know if you have any further questions!

**Comment by pdh930105** [comment]
Thank you for response! 

This work is interest and understand intuitively!
