### ISSUE TITLE
issue with running cifar10_dws_cnn. (INVALID instr.)

### ISSUE THREAD

**Issue by jypark1257** [alexmr09/Mixed-precision-Neural-Networks-on-RISC-V-Cores#7]
Hello, 

I have trouble with running cifar10_dws_cnn simulation.

I am using riscv64-unknown-elf-gcc with arch=rv32imc_zicsr, 

compiling was successful but when I tried to run the simulation, the simulation gave me the error "Illegal instruction". 

the trace gave me the instruction name "INVALID". 
![image](https://github.com/user-attachments/assets/df524d21-352f-4e9c-89c6-c09dc1fb07c7)
![image](https://github.com/user-attachments/assets/7d8c2739-34ca-466f-8e7c-c174eba7405d)

the cmsis_cnn simulations had no this kind of errors. 

Thank you for the great work.

**Comment by alexmr09** [comment]
Hello,

To address your issue, I recommend compiling the program using the riscv32-unknown-elf-gcc cross-compiler. Additionally, if you are not already doing so, it would be better to run the simulations using the demo system. The simple system was primarily designed for generating VCD traces during RTL simulations and may not be suitable for broader use cases.

Let me know if you have any further questions or need assistance!

**Comment by jypark1257** [comment]
After using demo system instead of simple system. It works without any error.

Thank you for the reply.
